language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: gnAbUmgcTRFZLrL2IJJEgEy6NlArwQRFToqIilOjhODmno97w1SU4U1sSd2EJp+2I+uMFzoHOC3K0YXqD9+/sSLQFwO1Osq6sKBhMcxwiBd7Cee05OZftrC/mu4PslwgFzMfs5d21rvgDVO/U1/4B8kn4WXu6Lb908tHMaQ/x6D3FpO81rk/AU5i0Ma4OqPQ1AQLwhSPQzn2JI1vhPl2nb/exIkR5TxWVZ5SU1m4T2nlJg/3LYmCESHT5RefqRW//5ZHU71XgMn287WgWSfJqU8WsmlPLum/E5AtmTYWTRsfdgt2kRuOk2RtMwoe8Xnl2MVAZ2Auwkkx++YYvy+a6SeiU3zj/QUdu9zuJOCEW68ONm+wunXS5emv2quJ25eB6FkzhdaRnN+FEOl4MH8zL1wZ/86A3RwUnLRPHFJxPWdiW5t9u95hhwDw+s/jf/oiaVCiz1LsH6X7jzKsg/ONaZZ1flKVYn1rc1+e9bMPpFTK1vpAYTCXhHiXchg4HMSoCJKEUMiqyiwUHxOkhTYDQJU+6wvaSb9YTnbMvbDJbf+Y2xeaq5fy8Fs2mAFZySnBkr5jU5D9J8e8EC3U4JXLWi4cTTbScpMgMmlqSA5n9J+n8wR10SzVGTTgmxzzTZniFPqKgvU57XB4xnTV4KsE7xw9TfBH6lospNuwQwZfjbA=

env:
  global:
    - secure: gyjXDi8awvanDrdKBEAldam5D1fT/UaNeEJnAA5mu/8nwNW/nsi9BeV+BRg/Ja4I63RH7avzBIkL/MYpSba8BPK7XzNTVSxAMmwTAEjVdFbczsBrY39hT+pLmND89iVKmN3pJ2A+6jSm1mbKEZIs9KTazasg08pwXAaaWDVv7sINsu0IxEhQsSvp9qyCZ/6pH+SAh2R5K4VOalTErbhnYeSzOUKnKiCSPp20zBCXZMJlDBtbEOHNYAv4vgWSjdiG0f67f9UlwnVGXwJQAb/r4C+a5MFJDnx7oxFBtpQhanHhafxCcqo+XcM80piMxz+8Rnwk0bMNctdFR7TMwBlwdAiGOh2cHQrAteE5Qgz2qZ2dMeQFhF0j2sX3imJjKn2VWrPK2d7Q4RleQXEM6Y7Fhrtr/iwhYv5Vw2Be4MNC7TqZt33gBUlI2hHr4NRl4ojqIlj2W0vsDJgtqDI109sKReZgrk2MkK2qhIXEudl/fibBVKMTKrwsfPHtFkypTfEnRB3ZeX31FWV8ItHk80PBsc3Ily4aT/MStMLrBAcFUEBwaYKjZRC6SbTwg6ibKRGb7uH87q+ZVNa2N/s2l+yqoNoJ4w54enH5LKeJia7Tf1CVnsF6IIj5jY9fauj7az7pmP9G+x/QNp5H/wU/IrCC3fC81aTz6ZuyX3ZxxlQ3rps=
    - secure: VOiwp9S4FZbeQtRu2bX2YFQ16e3RBp27HEC5gFVOozng1qL2oLbZsH2dl2ur5rEvvRGLmUz7hGXMMZeqLMntgP4fwRwz5ai4LK02ENDR1N6hd31u9S7Wwt3t+IuD4uYDvtpKOeEFqmjnOaEVkC6oTHhl42UsPYsLX4n2Zs7D3d8t4yI/OBQQqrQQQrmv42+pJWcejuuRYTMAvz91bGqHC2h9ceBcZhxxlxLTcKEk80ERnc2vCupJgSdZ/TmtZ+/wWTNw/oZxY50vKW5HNzfxPV10Fw7frLBoZScOEZ1PBR9bCOOsqWoL3htAHmZiZdr9ah3wF+frUEQobKTqLR5DCk7/VdcGuKQiykDpriGDdSHnKDIQcgQIjFKLkfIyQ5nPXoKvU2SkNtaozF/d+5wqhjQ+OIRaAkrlpKamvL7GVzfSR2lZDwZ2Kq4FCGBpDYhLCQZaRKkW6N9rxl9xTTCKuZFeCkH5TsdWekk4g9j/PRSjdaQaB9DEDWE24SgZF7wRZ1g/0y3Npek7aVTFJhgGnwrQSlpkJn88IGTI99VDXvX8sveKlnvfJKqXOvJty5ZqyBkPMR4OZy7MJxATA1t3P5NmEplpUnvh+xnRrq/cE5Qp0sDKLIHDiEq9gCmEMF362y4jx2eTxQ9GtV6hQcpVUbo5t+7+GIkkPAQo6Mek7Yw=
    - secure: TwCX0Z8xFkpes+Wh3ttkm7naTHFjct0Q6fCe7cLhUklKZboNrXALTlnmET/kxIaBL7ELe6qEodaqtEh+vs88o+iJL35rc7Ina9fpIoUuPqT/gwbd+MifC8MljxqBHeXMZ2UfvUhfwZi7/IJDAfKm42XEyErThViTjk9ly13XJveAzO2cA2Iewchydep8qbfND6MCgL0O1G42SgoL2+SKKtXL7+IiJa2TfsfixskIqO7oi2GinV3Mf0gxlynvCvcrhOTQ+Me1YC6sJLQWS9w0TbR7jh8C9bsMjkTfcUFbY0B3Q5axx++NNZFh6KTr/Eo9CIlXrSvdA386IRXo+MjGwQxkQtk716GyHEHpIZqTIxDLqYE3y251FRoDTDfwOPatk6xB1s8Yia2Fz1xnJ4lW8pQaKSHxk0se62g2wQMw810P37kduMAYOYmuPLqIxfoJ794bfxzvu2lOZCemf4SomCyiTWCDyPXqiDUWRjY0OTxTBSFbXqgdUOZsNPhE2IRxl/y1ootBdX2Riem3d+lpC9dcrDwr6sm/CXWFDDHmAyMhbWlbOhvpZw40ZrYi+Xv1Skwo1yIF1dHu4eKDU1aN9ddTc/PmreLYyrSt3V1ggUrprFLxDRjxrPESXqvTuC7xzW1k86/HBhJ+KE0R0hzvI8J6Z/x7VGrMak1CoeoF7vg=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
