language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: YCIu1jqBhFSdThlqR8jF25siKrfaGda2luT/2jkYT7iE4dfgchcJpyMgmcKHSupIXNKpbk8EkMWq85pVGDPQFmz3OcyupeZg5kI8WvDsWLz4b1kFRPbkB+Pc3mP3/hWgVLKNh75LTLNy6irC0u51fo7cPT4RclIQwo5rLzTIvdeKD+ma8Gm/Enuz6sCJuGvn+Je7tTcGxumQZrrpny3LIwuZvMHMWSjpGaLnv5bZ/dyyabr6/aA8zXoCgKur3pVAP

env:
  global:
    - secure: E3p+h5hnZKe7Oj1S/ISifmbIegShqlw/rn1b1gejyrEUjRn7Mr4mrIrGEyuWrw8g6jZ99MIcCqs+Wr/mYLybgcFKYhTenvuIIsMo9FRs6YlP+jbzlbPPZsl8uhVIOu4S5oklTln1b+MHVDDeT7y6SnJZMmr1xx6u82HXKXjC0MKqejn/Gvo2pn+ldw9ULNRxUnfqlyz88MibBgXotLOQkYmjmaAQvWDpiNPkm6ken+J375/27MkgL5Fq/Capx9+vb
    - secure: JI2CClNEaHdGfYrw7BjpQfYBpenDl6LY0fGQZ6h+7fNIlcb3Hm56/BUWzh0L8/nwl7m7EOkCrLuFwfgOBNE1qzhkHgb5D8oOu07tg1GPQGt0ug4faNYsSCtxjJ6jNrU/FW7xz3d6OZoFkWP+V2dJYpnz/leDQfmszVa/FSPu3o9p374ODHVD8/sf4fUCrVwjRJIReVjWp26NvGnU17YKpcFhSgM+HYKDcbxgWfo8KMs8Dwe71mCw41zDtFDjhfmNa
    - secure: S7J5c+r4awXGs6KR4MsHhTGZEta9o+LSIvY2rXy4f6sr6nV8BaRtaCW3X3lIAzxU9kPB4mFqLi/Zd10AIiE3HFdSeNRZeEu/aIOHQqiJpauwCnQJgbn9wMLgr5H2AnpmohJoW8i8BYd7/y+rxvj3vvh/G2Nd0nVaT/eFA7gExU+/wZPe6mndvT+mZDZQzWE4ikEpawIpMDRn35UnDgaRbzXq82v6x2ubJbIeCtnUYpeUvBfPC8u75HmQq7/3WyxAX
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
